<?php

namespace Database\Seeders;
use App\Models\Role;
use App\Models\User;
use App\Models\Permission;
use App\Models\UsersRoles;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use function Symfony\Component\Console\Style\table;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $developer = Role::where('name','Developer')->first();
        $publisher = Role::where('name','Publisher')->first();
        $manager = Role::where('name', 'Manager')->first();
        $createTasks = Permission::where('slug','create-tasks')->first();
        $manageUsers = Permission::where('slug','manage-users')->first();

        /*$user1 = new User();
        $user1->first_name = 'Vlad';
        $user1->last_name = 'Gko';
        $user1->login = 'vlad_gko';
        $user1->email = 'vladgko@gmail.com';
        $user1->congregation_id = '2';
        $user1->mobile_phone = '068484866';
        $user1->additional_phone = '068484866';
        $user1->gender = 0;
        $user1->hometown = 'Бельцы';
        $user1->city = 'Бельцы';
        $user1->address = 'Т. Владимиреску 51';
        $user1->birthday = '30-03-2001';
        $user1->christening_day = '15-08-2015';
        $user1->registration_date = Carbon::now();
        $user1->password = bcrypt('secret');
        $user1->save();
        $user1->roles()->attach($developer);
        $user1->permissions()->attach($createTasks);*/


        $array_Pamanteni = [
            'first_name' => [
                'Владислав',
                'Сергей',
                'Анатолий',
                'Валентина',
                'Дойна',
                'Екатерина',
                'Петр',
                'Игорь',
                'Николай',
                'Раиса',
                'Неля',
                'Александр',
                'Прасковья',
                'Галина',
                'Ирина',
                'Мария',
                'Корошан',
                'Яна',
                'Пянковский',
                'Оксана',
                'Алла',
                'Михаил',
                'Анна',
                'Надежда',
                'Галина',
                'Виктор',
                'Ирина',
                'Анастасия',
                'Михаил',
                'Настя',
                'Татьяна',
                'Магдалина',
                'Паламарюк',
                'Андрей',
                'Борис',
                'Наталья',
                'Оксана',
                'Татьяна',
                'Олег',
                'Лариса',
                'Анатолий',
                'Венера',
                'Алла',
                'Ксения',
                'Сергей',
                'Лариса',
                'Виктор',
                'Наталья',
                'Валентина',
                'Инна',
                'Наталья',
                'Валентина',
                'Анна',
                'Людмила',
                'Надежда',
                'Анатолий',
                'Лилия',
                'Екатерина',
                'Людмила',
                'Андрей',
                'Алла',
                'Андрей',
                'Марина',
                'Ольга',
                'Сергей',
                'Дмитрий',
                'Алина',
                'Татьяна',
                'Влад',
                'Татьяна',
                'Эдуард',
                'Светлана',
                'Виктория',
                'Татьяна',
                'Алина',
                'Сергей',
                'Алёна',
                'Илья',
                'Сергей',
                'Артур',
                'Думитрица',
                'Лучия',
                'Владислав',
                'Людмила',
                'Мария',
                'Михаил',
                'Алина',
                'Мария',
                'Любовь',
                'Мария',
                'Владимир',
                'Валентина',
                'Виктор',
                'Екатерина',
                'Александра',
                'Нина',
                'Тамара',
                'Татьяна',
                'Александр',
                'Анна',
                'Дмитрий',
            ],
            'last_name' => [
                'Головенко',
                'Головенко',
                'Головенко',
                'Головенко',
                'Головенко',
                'Головенко',
                'Адамчук',
                'Ануров',
                'Бабан',
                'Бабан',
                'Баркарь',
                'Баркарь',
                'Божко',
                'Букатару',
                'Бурдужа',
                'Бурлаку',
                'Валентина',
                'Ватрич',
                'Вячеслав',
                'Галюк',
                'Гриненко',
                'Дворский',
                'Деведенко',
                'Елизарова',
                'Епанова',
                'Зайцев',
                'Закирина',
                'Илащук',
                'Илащук',
                'Илащук',
                'Илащук',
                'Ильенко',
                'Илья',
                'Казаку',
                'Казаку',
                'Казаку',
                'Казаку',
                'Казаку',
                'Каратеев',
                'Каратеева',
                'Кобелев',
                'Кобелева',
                'Ковальская',
                'Ковальская',
                'Ковальский',
                'Коломеец',
                'Кольчугин',
                'Кольчугина',
                'Корошан',
                'Корошан',
                'Кузмицкая',
                'Куницкая',
                'Курекеру',
                'Кучерявая',
                'Кучерявая',
                'Кучерявый',
                'Куштан',
                'Лемешко',
                'Литинская',
                'Литинский',
                'Любонская',
                'Мандрик',
                'Мандрик',
                'Марчук',
                'Марчук',
                'Маценко',
                'Маценко',
                'Меленчук',
                'Митясов',
                'Митясова',
                'Мойса',
                'Мойса',
                'Мойса',
                'Одайник',
                'Оленец',
                'Оленец',
                'Паламарюк',
                'Паламарюк',
                'Паламарюк',
                'Паскал',
                'Паскал',
                'Паскал',
                'Повенский',
                'Полякова',
                'Рементова',
                'Ромашенко',
                'Рутковская',
                'Савчук',
                'Савчук',
                'Савчук',
                'Савчук',
                'Скобелкина',
                'Спыну',
                'Трипадуш',
                'Тучак',
                'Тучак',
                'Унгуряну',
                'Фёдорова',
                'Фомин',
                'Цуцук',
                'Цуцук',

            ],
            'login' => [
                'vlad_gko',
                'serghei.golovenco',
                'Anatoli',
                'Valna',
                'golovenkodoina',
                'n10c',
                'adamciuc.peotr',
                'anurov.igor',
                'Baban.Nikolai',
                'Raisababan',
                'Barcanelia',
                'Barcaria',
                'bojco.p',
                'bucataru',
                'Irina_79',
                'burlacumaria',
                'Valentina.Corosan',
                'Iana',
                'sloniara1976@gmail.com',
                'Galiucoxana',
                'Allagrin',
                'Toma',
                'dimanna',
                'Elizarova.Nadejda',
                'galinka1554@gmail.com',
                'Zaitevv',
                'Zakirina68',
                'ilasiuc.anastasia',
                'ilasciucmihail@gmail.com',
                'IlasciucNastia@gmail.com',
                'ilasciuctatiana@gmail.com',
                'ilmagd',
                'iliuhasan.004@gmail.com',
                'GRODDER',
                'Boris.cazacu@gmail.com',
                'kazakunatalia@gmail.com',
                'CazacuOxana',
                'Atelie',
                'oleg',
                'Karateeva',
                '1KobelevAA',
                'venera',
                'allacov',
                'kovalskayakseniia',
                'Serjik95kov@mail.ru',
                'colomeet.larisa',
                'colcugin.victor',
                'colciugin.natalia',
                'Corosan.Valentina',
                'corosan.inna',
                'Kuzmit',
                'cunitvalentina',
                'kurianna',
                'cuceriavaia.liudmila',
                'kucnadej',
                'cuceriavii.anatoli',
                'kustan.lilia',
                'lemeshecaterina',
                'Litinskaya',
                'litinsci.andrei',
                'luballa',
                'mandrandrei',
                'manmari',
                'marciuc.olga',
                'marciuc.serghei',
                'matencodmitrii',
                'matencoalina',
                'meltatiana',
                'Mitiasovvlad',
                'RisovanaiaTatiana',
                'MAN',
                'Moisas',
                'vicamoisa1@gmail.com',
                'odainic.tatiana',
                'Olenet',
                'Sergo',
                'palamariuc.aliona',
                'Palamariuc.Ilia',
                'palamariuc.serghei',
                'arci33',
                'paskal.dumitrisia',
                'arci34',
                'vpovenskii@bk.ru',
                'poliacova.liudmila',
                'Mariia3',
                'romasenco.mihail',
                'Malina',
                'maria58',
                'Liubov',
                'savmar55@yandex.ru',
                'Vova',
                'scobelkina.valentina',
                'vispy',
                'tripadus.ecaterina',
                'Sasha',
                'Tuceac',
                'tamara.ungurianu',
                'fiodorova.tatiana',
                'AlexFomin',
                'ann.c90k@gmail.com',
                'miteaniuta@gmail.com',
            ],
            'email' => [
                'golovencovladislav@gmail.com',
                'golovenco.serghei@gmail.com',
                'anvest@list.ru',
                'Sanbigvalna@gmail.com',
                'doinagolovenko@gmail.com',
                '51empty@email.com',
                '64empty@email.com',
                '1empty@email.com',
                '2empty@email.com',
                '49empty@email.com',
                '3empty@email.com',
                'sansanicis1@gmail.com',
                '4empty@email.com',
                '5empty@email.com',
                '65empty@email.com',
                '6empty@email.com',
                '7empty@email.com',
                'ianavatrici@gmail.com',
                'sloniara1976@gmail.com',
                '50empty@email.com',
                '52empty@email.com',
                '53empty@email.com',
                '8empty@email.com',
                '9empty@email.com',
                'galinka1554@gmail.com',
                'Zvictor@mail.ru',
                'zakirinaira@gmail.com',
                '10empty@email.com',
                'ilasciucmihail@gmail.com',
                'IlasciucNastia@gmail.com',
                'ilasciuctatiana@gmail.com',
                '11empty@email.com',
                'iliuhasan.04@gmail.com',
                '54empty@email.com',
                'Boris.cazacu@gmail.com',
                'kazakunatalia@gmail.com',
                'negruoxana6@gmail.com',
                'tkazaku1@gmail.com',
                'Karateev128@mail.com',
                '55empty@email.com',
                '12empty@email.com',
                '13empty@email.com',
                '56empty@email.com',
                '57empty@email.com',
                'Serjik95kov@mail.ru',
                '14empty@email.com',
                '15empty@email.com',
                '16empty@email.com',
                '17empty@email.com',
                '18empty@email.com',
                '19empty@email.com',
                '20empty@email.com',
                '21empty@email.com',
                '22empty@email.com',
                '23empty@email.com',
                '24empty@email.com',
                '25empty@email.com',
                '26empty@email.com',
                '58empty@email.com',
                '27empty@email.com',
                '28empty@email.com',
                '29empty@email.com',
                'mandmari@mail.ru',
                '30empty@email.com',
                '31empty@email.com',
                '32empty@email.com',
                'alin-go@mail.ru',
                '33empty@email.com',
                'miteasov@gmail.com',
                'miteasovat@gmail.com.',
                '34empty@email.com',
                '59empty@email.com',
                'vicamoisa1@gmail.com',
                '35empty@email.com',
                '60empty@email.com',
                'sergo373@mail.ru',
                '36empty@email.com',
                '37empty@email.com',
                '38empty@email.com',
                '39empty@email.com',
                '40empty@email.com',
                '41empty@email.com',
                'vpovenskii@bk.ru',
                '42empty@email.com',
                '61empty@email.com',
                '43empty@email.com',
                '62empty@email.com',
                '44empty@email.com',
                'liubakolteniuk@mail.ru',
                'savmar55@yandex.ru',
                'Vallidimar@mail.ru',
                '45empty@email.com',
                'thebeardrake@gmail.com',
                '46empty@email.com',
                '47empty@email.com',
                '63empty@email.com',
                'tamaraungurianu98@gmail.com',
                '48empty@email.com',
                'alexandru.fomin@gmail.com',
                'ann.c90k@gmail.com',
                'miteaniuta@gmail.com',
            ],
            'password' => [
                bcrypt( 'secret'),
                bcrypt( 's3ygRu326632663'),
                bcrypt( '123qW456'),
                bcrypt( '123zx456'),
                bcrypt( '123A456'),
                bcrypt( '123katy4'),
                bcrypt( '123P456'),
                bcrypt( '123Q456'),
                bcrypt( '8650737832'),
                bcrypt( '236236'),
                bcrypt( '098765n'),
                bcrypt( '7571702659'),
                bcrypt( '069229525'),
                bcrypt( '068955656'),
                bcrypt( 'lerocka2008'),
                bcrypt( '236236'),
                bcrypt( '1111385435'),
                bcrypt( '2309851775'),
                bcrypt( '564738slon'),
                bcrypt( '123A456'),
                bcrypt( 'l89m92t10'),
                bcrypt( '0'),
                bcrypt( '2005924567'),
                bcrypt( '790277'),
                bcrypt( 'no61ki31a'),
                bcrypt( '123123'),
                bcrypt( '211761831'),
                bcrypt( '079709743m'),
                bcrypt( '4050019074'),
                bcrypt( 'nastia069894864'),
                bcrypt( '068379792t'),
                bcrypt( '3177847854'),
                bcrypt( 'IliuhaSan12'),
                bcrypt( 'titan11071988'),
                bcrypt( '299365'),
                bcrypt( '236236'),
                bcrypt( 'cazacuoxana24'),
                bcrypt( '4685852744'),
                bcrypt( '456321'),
                bcrypt( 'Lorik75'),
                bcrypt( 'KAV1965kWa'),
                bcrypt( 'venera68'),
                bcrypt( '2369100cs'),
                bcrypt( 'yyvR33TQNrj'),
                bcrypt( '23691002369100cs!'),
                bcrypt( '2101860275'),
                bcrypt( 'leartsi01'),
                bcrypt( 'leartsi01'),
                bcrypt( '2503198726'),
                bcrypt( '123R654'),
                bcrypt( '987987'),
                bcrypt( '5886189868'),
                bcrypt( '857297924'),
                bcrypt( 'ajuju22PLease'),
                bcrypt( '6373552429'),
                bcrypt( 'GasLam57'),
                bcrypt( 'N3p7J5Y84'),
                bcrypt( '3876998241'),
                bcrypt( 'liudmila'),
                bcrypt( 'andrei1'),
                bcrypt( 'alla123'),
                bcrypt( '8835401967'),
                bcrypt( '8232298814'),
                bcrypt( '4100mama'),
                bcrypt( '31003100mar'),
                bcrypt( 'alinavadim1'),
                bcrypt( 'Standalina80'),
                bcrypt( '1243957048'),
                bcrypt( '9132059227'),
                bcrypt( '123a654'),
                bcrypt( '5516org'),
                bcrypt( 'sv12345'),
                bcrypt( '12697vm'),
                bcrypt( '5113687714'),
                bcrypt( 'gabriela93'),
                bcrypt( '2004801408'),
                bcrypt( 'aliona79'),
                bcrypt( '156156'),
                bcrypt( 'serghei73'),
                bcrypt( '078335875'),
                bcrypt( 'Dumi123654'),
                bcrypt( '123A654'),
                bcrypt( '2784399a'),
                bcrypt( '123A456'),
                bcrypt( '123R456'),
                bcrypt( '123E456'),
                bcrypt( 'Alina25'),
                bcrypt( 'Na19dej79da'),
                bcrypt( 'liubov10'),
                bcrypt( '9440887201'),
                bcrypt( 'savcec'),
                bcrypt( 'vs060078341'),
                bcrypt( 'toyo156STEND145'),
                bcrypt( '6374795352'),
                bcrypt( 'alexaeaea2019'),
                bcrypt( 'ninuleaninulea60'),
                bcrypt( '6323538317'),
                bcrypt( '7876827038'),
                bcrypt( '9773505646'),
                bcrypt( '2325526393'),
                bcrypt( '6884554975'),

            ],
            'congregation_id' => [
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
            ],
        ];

        $array = [
            'first_name' => ['first', 'second'],
            'last_name' => ['deo', 'feo'],
            'info' => [
                json_encode(['mobile_phone' => '4567987', 'city' => 'mycity']),
                json_encode(['mobile_phone' => '4567987', 'city' => 'mycity'])],
        ];

        $er = ["city": "Бельцы",
            "gender": "male",
            "country": "Moldova",
            "last_login": "2023-08-31 17:49:53",
            "mobile_phone": "068484866",
            "additional_phone": "068484866",
            "address",
            "birth_day",
            "christening_day",
            'registration_date'
        ];


        foreach($array_Pamanteni['first_name'] as $key => $value){
            $user = new User();
            $user->first_name = $value;
            $user->last_name = $array_Pamanteni['last_name'][$key];
            $user->login = $array_Pamanteni['login'][$key];
            $user->email = $array_Pamanteni['email'][$key];
            $user->congregation_id = $array_Pamanteni['congregation_id'][$key];
            $user->password = $array_Pamanteni['password'][$key];
            $user->save();
            $user->roles()->attach($publisher);
        }


    }
}
